[book]
authors = ["Kia Strawberries"]
language = "en"
multilingual = false
src = "src"
title = "Twilight Experiments"

[output.html]
edit-url-template = "https://uwukia.github.io/twilight-experiments/{path}"